name: ben-northern
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23273
title: Ben Northern Fine Arts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05080d'
    - '#192f6b'
    - '#dfe4f6'
    - '#3768a7'
    - '#929cca'
  brandStrength: 0.0762518816627562
  lightness: 0.43125378829427063
  saturation: 0.1409762278199196
  rhythmicContrast: 0.17381687415763736
purpose: []
